[package]
name = "mustachers"
version = "0.1.0"
edition = "2021"
authors = ["Sam French <Sam.French@bbc.co.uk>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
mustache = "0.9.0"
